### ISSUE TITLE
undefined symbol: hb_ft_font_changed

### ISSUE THREAD

**Issue by jamespo** [oleastre/kitty#1]
From the f27 copr package (0.8.4) I get:

$ kitty
Traceback (most recent call last):
  File "/usr/lib64/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib64/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/bin/../lib64/kitty/__main__.py", line 68, in <module>
    main()
  File "/usr/bin/../lib64/kitty/__main__.py", line 61, in main
    from kitty.main import main
  File "/usr/bin/../lib64/kitty/kitty/main.py", line 10, in <module>
    from .borders import load_borders_program
  File "/usr/bin/../lib64/kitty/kitty/borders.py", line 8, in <module>
    from .fast_data_types import (
ImportError: /usr/bin/../lib64/kitty/kitty/fast_data_types.so: undefined symbol: hb_ft_font_changed

**Comment by jamespo** [comment]
Actually I may see the issue, version of harfbuzz with f27 is 1.4.8 & docs specify 1.5.0+ so this cannot work on standard f27

**Comment by oleastre** [comment]
Yes for fedora 27, you need to update harfbuzz. (I have a backported version in the same copr repository).
After adding the copr repository, a simple `dnf upgrade harfbuzz` should solve the issue
